name: myrelease

on: 
  push:
    branches:

env:
  BIN: testsetup
  EXTRAFILES: docs/ examples/
permissions: write-all

jobs:

     
  myrelease:
    runs-on: windows-latest
    steps:
      - run: |
          $targets=@(
          [pscustomobject]@{GOOS="windows";GOARCH="AMD64"},
          [pscustomobject]@{GOOS="windows";GOARCH="386"},
          [pscustomobject]@{GOOS="windows";GOARCH="ARM64"},
          [pscustomobject]@{GOOS="android";GOARCH="AMD64"},
          [pscustomobject]@{GOOS="linux";GOARCH="amd64"},
          [pscustomobject]@{GOOS="linux";GOARCH="386"},
          [pscustomobject]@{GOOS="darwin";GOARCH="arm64"},
          )
          foreach ($target in $targets){
          echo $target.GOOS
          }
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: install go-msi
        run: choco install go-msi
      - name: get the version
        id: curver
        run: |
          $v = $(git for-each-ref --sort=-creatordate --count 1 --format="%(refname:short)" "refs/tags/v*")
          echo "ver=$(echo $v)" >> $env:GITHUB_OUTPUT
      - name: bump semver
        uses: actions-ecosystem/action-bump-semver@v1
        id: bumpver
        with:
          current_version: ${{ steps.curver.outputs.ver }}
          level: major
      - name: build-win-amd64
        run: go build -v -o bin/win64/${{env.BIN}}.exe
      - name: build-win32
        run: |
          $env:GOARCH="386"
          go build -v -o bin/win32/${{env.BIN}}.exe
      - name: build-android-arm64
        run: |
          $env:GOOS="android"
          $env:GOARCH="arm64"
          go build -v -o bin/android-arm64/${{env.BIN}}
      - name: build linux-x86
        run: |
          $env:GOOS="linux"
          $env:GOARCH="386"
          go build -v -o bin/linux-x86/${{env.BIN}}
      - name: build linux-amd64
        run: |
          $env:GOOS="linux"
          $env:GOARCH="amd64"
          go build -v -o bin/linux-amd64/${{env.BIN}}
      - name: build darwin/amd64
        run: |
          $env:GOOS="darwin"
          $env:GOARCH="amd64"
          go build -v -o bin/darwin-amd64/${{env.BIN}}
      - name: build darwin/arm64
        run: |
          $env:GOOS="darwin"
          $env:GOARCH="arm64"
          go build -v -o bin/darwin-arm64/${{env.BIN}}
      - name: build MSIs
        run: |
          $env:Path += ";C:\Program Files\go-msi;C:\Program Files (x86)\WiX Toolset v3.11\bin"
          $env:TMP = "${{ runner.temp }}"
          $env:Tempdir = "${{ runner.temp }}"
          go-msi.exe make -p wix64.json -a amd64 --msi ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-setup-amd64.msi --version 1.0.2
          go-msi.exe make -p wix86.json -a 386 --msi ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-setup-x86.msi --version 1.0.2
      - name: pack things to zip
        run: |
          7z a ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-windows-amd64.zip "./bin/win64/${{env.BIN}}.exe" ${{env.EXTRAFILES}}
          7z a ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-windows-x86.zip "./bin/win32/${{env.BIN}}.exe" ${{env.EXTRAFILES}}
          7z a ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-android-arm64.zip ./bin/android-arm64/${{env.BIN}} ${{env.EXTRAFILES}}
          7z a ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-linux-amd64.zip ./bin/linux-amd64/${{env.BIN}} ${{env.EXTRAFILES}}
          7z a ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-linux-x86.zip ./bin/linux-x86/${{env.BIN}} ${{env.EXTRAFILES}}
          7z a ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-darwin-amd64.zip ./bin/darwin-amd64/${{env.BIN}} ${{env.EXTRAFILES}}
          7z a ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-darwin-arm64.zip ./bin/darwin-arm64/${{env.BIN}} ${{env.EXTRAFILES}}
      - name: push the tag
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ steps.bumpver.outputs.new_version }}
          git push --tags
      - name: release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ steps.bumpver.outputs.new_version }}
          files: |
            ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-windows-amd64.zip
            ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-windows-x86.zip
            ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-setup-x86.msi
            ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-setup-amd64.msi
            ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-android-arm64.zip
            ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-linux-amd64.zip
            ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-linux-x86.zip
            ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-darwin-amd64.zip
            ${{env.BIN}}-${{ steps.bumpver.outputs.new_version }}-darwin-arm64.zip