name: myrelease

on: 
  push:
    branches:

env:
  BIN: testsetup
  EXTRAFILES: docs/ examples/
permissions: write-all

jobs:

     
  myrelease:
    runs-on: windows-latest
    steps:
      - run: echo "a ${{BIN}}-windows-amd64.zip this is test"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: install go-msi
        run: choco install go-msi
      - name: build-win-amd64
        run: go build ${{BIN}}.go -v -o bin/win64/${{BIN}}.exe
      - name: build-win32
        run: |
          $env:GOARCH="386"
          go build ${{BIN}}.go -v -o bin/win32/${{BIN}}.exe
      - name: build-android-arm64
        run: |
          $env:GOOS="android"
          $env:GOARCH="arm64"
          go build ${{BIN}}.go -v -o bin/android-arm64/${{BIN}}
      - name: build MSIs
        run: |
          $env:Path += ";C:\Program Files\go-msi;C:\Program Files (x86)\WiX Toolset v3.11\bin"
          $env:TMP = "${{ runner.temp }}"
          $env:Tempdir = "${{ runner.temp }}"
          go-msi.exe make -p wix64.json -a amd64 --msi ${{BIN}}-setup-amd64.msi --version 1.0.2
          go-msi.exe make -p wix86.json -a 386 --msi ${{BIN}}-setup-x86.msi --version 1.0.2
      - name: pack things to zip
        run: |
          7z a ${{BIN}}-windows-amd64.zip "./bin/win64/${{BIN}}.exe" ${{env.EXTRAFILES}}
          7z a ${{BIN}}-windows-x86.zip "./bin/win32/${{BIN}}.exe" ${{env.EXTRAFILES}}
          7z a ${{BIN}}-android-arm64.zip ./bin/android-arm64/${{BIN}} ${{env.EXTRAFILES}}
      - name: get the version
        id: curver
        run: |
          $v = $(git for-each-ref --sort=-creatordate --count 1 --format="%(refname:short)" "refs/tags/v*")
          echo "ver=$(echo $v)" >> $env:GITHUB_OUTPUT
          
      - name: show version
        run: Write-Output ${{ steps.curver.outputs.ver }}
      - name: bump semver
        uses: actions-ecosystem/action-bump-semver@v1
        id: bumpver
        with:
          current_version: ${{ steps.curver.outputs.ver }}
          level: major
      - name: push the tag
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ steps.bumpver.outputs.new_version }}
          git push --tags
      - name: release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ steps.bumpver.outputs.new_version }}
          files: |
            ${{BIN}}-windows-amd64.zip
            ${{BIN}}-android-arm64.zip
            ${{BIN}}-windows-x86.zip
            ${{BIN}}-setup-x86.msi
            ${{BIN}}-setup-amd64.msi