name: myrelease

on: 
  push:
    tags:
      - '*'

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  myrelease:
    runs-on: windows-latest
    steps:
      -name: wix path
        run: |
          $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"
      - name: candle
        run: light
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: tidy
        run: go mod tidy -v
      - name: build-w64
        run: go build -v -x
      - name: pack things to zip
        run: 7z a testsetup-w64.zip testsetup.exe docs/ examples/
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            testsetup.exe
            testsetup-w64.zip
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}