name: myrelease

on: 
  push:
    tags:
      - '*'
env:
  BIN: testsetup
  DIRS: docs/ examples/
permissions:
  contents: write

jobs:
  myrelease:
    runs-on: windows-latest
    steps:
      - name: Download go-msi
        run: aria2c https://github.com/mh-cbon/go-msi/releases/download/1.0.2/go-msi-amd64.msi
      - name: install go-msi
        run: Start-Process msiexec -ArgumentList "/i go-msi-amd64.msi /qn /L*v msi.log" -NoNewWindow -Wait
      - name: show log
        run: cat -Path msi.log
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: build-win-amd64
        run: go build -v -o bin/win64/${{env.BIN}}.exe
      - name: build-win32
        run: |
          $env:GOARCH="386"
          go build -v -o bin/win32/${{env.BIN}}.exe
      - name: build go-msi and MSIs
        run: |
          $env:Path += ";C:\Program Files\go-msi;C:\Program Files (x86)\WiX Toolset v3.11\bin"
          $env:TMP = "${{ runner.temp }}"
          $env:Tempdir = "${{ runner.temp }}"
          go-msi.exe check-env
          go-msi.exe make -p wix64.json -a amd64 --msi ${{env.BIN}}-setup-amd64.msi --version 1.0.2
          go-msi.exe make -p wix86.json -a 386 --msi ${{env.BIN}}-setup-x86.msi --version 1.0.2
      - name: pack things to zip
        run: |
          7z a ${{env.BIN}}-amd64.zip bin/win64/${{env.BIN}}.exe ${{env.DIRS}}
          7z a ${{env.BIN}}-x86.zip bin/win32/${{env.BIN.exe}} ${{env.DIRS}}
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{env.BIN}}-amd64.zip
            ${{env.BIN}}-x86.zip
            ${{env.BIN}}-setup-x86.msi
            ${{env.BIN}}-setup-amd64.msi
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}